import joblib
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, roc_curve, auc
import matplotlib.pyplot as plt

def build_attack_model():
    print("Loading extracted confidence scores...")
    # Load the data generated by the Shadow Model
    X = np.load('attack_X.npy')
    y = np.load('attack_y.npy')
    
    # We split this shadow dataset. 
    # 70% to train the attack model, 30% to test how good the attack is.
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    
    print("\nTraining the Attack Model (Random Forest)...")
    attack_model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
    attack_model.fit(X_train, y_train)
    
    print("Evaluating attack success...")
    # Get standard predictions (1 or 0)
    y_pred = attack_model.predict(X_test)
    # Get probability of being a member (for the ROC curve)
    y_prob = attack_model.predict_proba(X_test)[:, 1] 
    
    # 1. Print Numerical Results for the Report
    accuracy = accuracy_score(y_test, y_pred)
    print(f"\n======================================")
    print(f"🗡️ ATTACK ACCURACY: {accuracy * 100:.2f}%")
    print(f"======================================")
    
    print("\nDetailed Classification Report:")
    print(classification_report(y_test, y_pred, target_names=['Non-Member (0)', 'Member (1)']))
    
    # 2. Generate and Save the ROC Curve Plot
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    roc_auc = auc(fpr, tpr)
    
    plt.figure(figsize=(8, 6))
    plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
    plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Membership Inference Attack - ROC Curve')
    plt.legend(loc="lower right")
    plt.grid(True, alpha=0.3)
    
    # Save the plot as an image
    plt.savefig('attack_roc_curve.png', dpi=300, bbox_inches='tight')
    print("\n✅ Saved ROC curve plot as 'attack_roc_curve.png'.")
    # Save the trained Random Forest model
    joblib.dump(attack_model, 'attack_model.joblib')

if __name__ == "__main__":
    build_attack_model()